version: "3"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: builder
    volumes:
      - ./src:/app/src
  sever:
    container_name: app-prod
    image: app-prod
    build:
      context: .
      target: server
    ports:
      - "3000:80"