name: Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - deploy
  pull_request:
    branches: 
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: "road-triper"

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2


    # Build front
    - name:  build front
      run: |
        yarn build:front:lin

    - name: Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: "taquet.erwan@gmx.fr"
    # Push the Docker image to Heroku Container Registry
    - name: Deploy
      run: |
        heroku git:remote -a road-triper
        git push heroku deploy:master
        
