name: Test

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - dev
      - feature/test
  pull_request:
    branches: 
      - master
      
jobs:
      
  Test:
    name: Test api
    runs-on: ubuntu-18.04
    steps:

    # Launch test
    - name: test
      run: |
        cd api
        yarn start:test
        yarn test:e2e
        yarn run test:cov
