name: Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - feature/dockerizing_react
  pull_request:
    branches: 
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: "road-triper"

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: |
        cd front
        docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/my-awesome-app/my-app .
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    # Push the Docker image to Heroku Container Registry
    - name: Deploy
      run: |
        cd front
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
